config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get 'loaderio-6740bbace59df2ad01bb669b65e8333e', controller: :loader_io, action: :verify

  resources :passwords, controller: 'clearance/passwords', only: %i(new create)
  resource :session, controller: 'clearance/sessions', only: %i(create) do
    resource :u2f, controller: 'u2f_sessions', only: %i(new create)
  end

  resources :users, controller: 'clearance/users', only: %i(create) do
    resource :password,
             controller: 'clearance/passwords',
             only: %i(create edit update)
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out_get'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  resources :artists, only: %i(new create index)
  resources :collections, only: %i(show edit update new create) do
    resources :pendants, only: %i(show)
  end

  resources :colors, only: %i(index show new create)

  namespace :my, module: :current_user do
    resources :pendants, only: %i(new create index show edit update) do
      resource :colors, only: %i(new create), controller: 'pendant_colors'
    end
    resources :pendant_records, only: %i(new create index)
    resources :fake_pendant_records, only: %i(new create)
    resources :artists, only: %i(index)

    resource :last_week_in_pendants, only: %i(show)

    resources :u2f_registrations, only: %i(new create)

    resource :settings, only: %i(show)
  end

  namespace :api do
    namespace :my, module: :current_user do
      resources :push_notification_subscriptions, only: %i(create)
      resource :pendant_record_status, only: %i(show)
    end
  end
end

app/controllers/api/current_user/pendant_record_statuses_controller.rb
# frozen_string_literal: true

module Api
  module CurrentUser
    class PendantRecordStatusesController < ApplicationController
      def show
        if current_user
          render json: { pendant_recorded?: current_user.recorded_pendant_today? }
        else
          render json: { error: 'Not Authorized' }, status: 401
        end
      end

      private

      def current_user
        super || decoded_token_user
      end

      def decoded_token_user
        decoded_token['user_id'] && User.find_by(id: decoded_token['user_id'])
      end

      def decoded_token
        if auth_header.present?
          JWT.decode(auth_header, Rails.application.secrets.secret_key_base).first
        else
          {}
        end
      end

      def auth_header
        request.headers['Authorization']
      end
    end
  end
end

app/controllers/api/current_user/push_notification_subscriptions_controller.rb
# frozen_string_literal: true

module Api
  module CurrentUser
    class PushNotificationSubscriptionsController < ApplicationController
      def create
        current_user.push_notification_subscriptions.find_or_create_by!(push_params)
        head :no_content
      end

      private

      def push_params
        params.permit(:endpoint, :p256dh, :auth)
      end
    end
  end
end

app/controllers/current_user/artists_controller.rb
# frozen_string_literal: true

module CurrentUser
  class ArtistsController < ApplicationController
    before_action :require_login

    def index
      @artists = artists.sort_by { |artist| artist.name.downcase }
      @chart_data = Artist.where(id: artists).joins(:glass_art_pieces)
                          .group('Artists.id', 'Artists.name').order('count_all DESC').limit(10).count.map { |k, v| [k.last, v] }
    end

    private

    def artists
      Artist.joins(:glass_art_pieces).merge(current_user.glass_art_pieces).uniq
    end
  end
end

app/controllers/current_user/fake_pendant_records_controller.rb
# frozen_string_literal: true

module CurrentUser
  class FakePendantRecordsController < ApplicationController
    before_action :require_login

    def new
      @pendant_record = current_user.pendant_records.new
      @pendants = current_user.glass_art_pieces
    end

    def create
      @pendant_record = current_user.pendant_records.new
      if @pendant_record.update pendant_record_params
        redirect_to my_pendant_records_path
      else
        @pendants = current_user.glass_art_pieces
        render :new
      end
    end

    private

    def pendant_record_params
      params.require(:pendant_record).permit(:pendant_id, :worn_on)
    end
  end
end

app/controllers/current_user/last_week_in_pendants_controller.rb
# frozen_string_literal: true

module CurrentUser
  class LastWeekInPendantsController < ApplicationController
    def show
      last_week_in_pendants = LastWeekInPendantsImage.new user: current_user

      respond_to do |format|
        format.html { send_data(last_week_in_pendants.html, type: 'text/html', disposition: 'inline') }
        format.png { send_data(last_week_in_pendants.to_png, type: 'image/png', disposition: 'inline') }
        format.jpg { send_data(last_week_in_pendants.to_jpeg, type: 'image/jpeg', disposition: 'inline') }
      end
    end
  end
end

app/controllers/current_user/pendant_colors_controller.rb
# frozen_string_literal: true

module CurrentUser
  class PendantColorsController < ApplicationController
    def new
      @pendant = GlassArtPiece.find params[:pendant_id]
      @color = Color.new
    end

    def create
      @pendant = GlassArtPiece.find params[:pendant_id]
      @color = Color.new create_params.merge(glass_art_pieces: [@pendant])
      if @color.save
        redirect_to my_pendant_path(@pendant)
      else
        render :new
      end
    end

    private

    def create_params
      Color::Params.new(params.require(:color).permit(:name, artist_ids: [])).attrs
    end
  end
end

app/controllers/current_user/pendant_record_photos_controller.rb
# frozen_string_literal: true
module CurrentUser
  class PendantRecordPhotosController < ApplicationController
    before_action :require_login

    def new
      @pendant_record = current_user.pendant_records.find(pendant_record_id)
      @photo = Photo.new
    end

    def create
      @pendant_record = current_user.pendant_records.find(pendant_record_id)
      @photo = Photo.new photo_params
      @pendant_record.photo = @photo
      if @pendant_record.save
        redirect_to my_pendant_records_path
      else
        render :new
      end
    end

    private

    def pendant_record_id
      params[:pendant_record_id]
    end

    def photo_params
      params.require(:photo).permit(:photo).merge(user: current_user)
    end
  end
end

app/controllers/current_user/pendant_records_controller.rb
# frozen_string_literal: true

module CurrentUser
  class PendantRecordsController < ApplicationController
    before_action :require_login

    def new
      @pendant_record = current_user.pendant_records.new
      @pendants = current_user.glass_art_pieces
    end

    def create
      @photo = current_user.photos.new photo_params
      @pendant_record = current_user.pendant_records.new pendant_record_params
      @pendant_record.photo = @photo if @photo.valid?
      if @pendant_record.save
        redirect_to action: :index
      else
        @pendants = current_user.glass_art_pieces
        render :new
      end
    end

    def index
      @calendar = calendar
    end

    private

    def calendar_hash
      {
        date: params[:date].try(:to_date) || Date.today,
        user: current_user
      }
    end

    def calendar
      PendantRecordCalendar.new calendar_hash
    end

    def photo_params
      params.require(:pendant_record).permit(:photo)
    end

    def pendant_record_params
      params.require(:pendant_record).permit(:pendant_id)
    end
  end
end

app/controllers/current_user/pendants_controller.rb
# frozen_string_literal: true

module CurrentUser
  class PendantsController < ApplicationController
    before_action :require_login

    def index
      @pendants = current_user.glass_art_pieces
      @chart_data = current_user.pendant_records.group(:pendant).count.sort.map { |k, v| [k.name, v] }
    end

    def show
      @pendant = current_user.glass_art_pieces.find params[:id]
    end

    def new
      @pendant = GlassArtPiece.new
    end

    def edit
      @pendant = current_user.glass_art_pieces.find params[:id]
      render :new
    end

    def create
      @pendant = GlassArtPiece.new
      if @pendant.update pendant_attrs
        redirect_to action: :index
      else
        render :new
      end
    end

    def update
      @pendant = current_user.glass_art_pieces.find params[:id]
      if @pendant.update pendant_attrs
        redirect_to action: :index
      else
        render :new
      end
    end

    private

    def pendant_attrs
      GlassArtPiece::Params::Pendant.new(create_params).attrs
    end

    def create_params
      params.require(:glass_art_piece).permit(:name, :collection_id, artist_ids: [], color_ids: [])
    end
  end
end

app/controllers/current_user/settings_controller.rb
# frozen_string_literal: true

module CurrentUser
  class SettingsController < ApplicationController
    before_action :require_login

    def show
      render
    end
  end
end

app/controllers/current_user/u2f_registrations_controller.rb
# frozen_string_literal: true

module CurrentUser
  class U2fRegistrationsController < ApplicationController
    before_action :require_login

    def new
      @registration_requests = u2f.registration_requests
      session[:challenges] = @registration_requests.map(&:challenge)

      key_handles = U2fRegistration.all.pluck(:key_handle)
      @sign_requests = u2f.authentication_requests(key_handles)
    end

    def create
      response = U2F::RegisterResponse.load_from_json(u2f_registration_params[:response])

      reg = begin
        u2f.register!(session[:challenges], response)
      rescue U2F::Error => e
        @error_message = "Unable to register: #{e.class.name}"
      ensure
        session.delete(:challenges)
      end

      U2fRegistration.create!(
        user: current_user,
        certificate: reg.certificate,
        key_handle:  reg.key_handle,
        public_key:  reg.public_key,
        counter:     reg.counter
      )

      redirect_to root_path
    end

    private

    def u2f
      @u2f ||= U2F::U2F.new(request.base_url)
    end

    def u2f_registration_params
      params.require(:u2f_registration).permit(:response)
    end
  end
end

app/controllers/pendants_controller.rb
# frozen_string_literal: true

class PendantsController < ApplicationController
  def show
    @pendant = GlassArtPiece.wearable.where(collection_id: params[:collection_id]).find(params[:id])
  end
end

app/views/current_user/pendants/_pendant.html.erb
<tr>
  <td><%= pendant.name %></td>
  <td><%= pendant.artist.name %></td>
  <td><%= pendant.pendant_records.count %></td>
</tr>

app/views/current_user/pendants/_pendant_record.html.erb
<div class="pendant-record card text-center p-3 m-0">
  <%= image_tag pendant_record.photo.url, class: 'card-img-top img-fluid', data: { src: pendant_record.photo.url } if pendant_record.photo.present? %>
  <div class="card-body">
    <p class="card-text">Worn On: <%= pendant_record.worn_on.strftime('%A, %B %-d, %Y') %></p>
    <p class="card-text text-muted">Created at: <%= pendant_record.created_at.strftime('%A, %B %-d, %Y at %I:%M%p') %></p>
  </div>
</div>

app/views/current_user/pendants/_pendant_row.html.erb
<tr>
  <td><%= link_to pendant.name, my_pendant_path(pendant) %></td>
  <td><%= pendant.artist_name %></td>
  <td>
    <% pendant.colors.sort_by(&:name).each_with_index do |color, i| %>
      <%= link_to color.name, color_path(color) %>
      <%= ' & ' unless pendant.colors.count - 1 == i %>
    <% end %>
  </td>
  <td><%= pendant.pendant_records.count %></td>
</tr>

app/views/current_user/pendants/_pendant_table.html.erb
<tr>
  <td><%= link_to pendant.name, my_pendant_path(pendant) %></td>
  <td><%= pendant.artist_name %></td>
  <td><%= pendant.pendant_records.count %></td>
</tr>

app/views/current_user/pendants/index.html.erb
<%= content_for :active_tab, :pendants %>

<div class="pendants">

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Total Number of Pendants</h5>
      <p class="card-text"><%= @pendants.count %></p>
      <%= link_to 'New Pendant', new_my_pendant_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#table" role="tab">Table</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#graphs" role="tab">Graphs</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content mt-1">
    <div class="tab-pane active" id="table" role="tabpanel">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th>Artist Name</th>
            <th>Colors</th>
            <th>Times Worn</th>
          </tr>
          </thead>
          <tbody>
          <%= render partial: 'pendant_row', collection: @pendants, as: :pendant %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="tab-pane" id="graphs" role="tabpanel">
      <figure class="figure pendants__chart">
        <figcaption class="figure-caption">Number of Times Worn by Pendant</figcaption>
        <%= pie_chart @chart_data %>
      </figure>
    </div>
  </div>
</div>

app/views/current_user/pendants/new.html.erb
<%= content_for :active_tab, :pendants %>

<%= simple_form_for [:my, @pendant], url: (@pendant.persisted? ? my_pendant_path(id: @pendant) : my_pendants_path) do |f| %>

  <label for="glass_art_piece[artist_ids][]">
    Artists
  </label>
  <input type="hidden" name="glass_art_piece[artist_ids][]" value="" />
    <%= react_component('GlassySelect',
        name: 'glass_art_piece[artist_ids][]',
        placeholder: 'Who made this pendant?',
        multi: true,
        value: @pendant.artist_ids,
        options: Artist.all.map { |a| { value: a.id, label: a.name} })
    %>

    <label for="glass_art_piece[collection_id]">
      Collection
    </label>
    <%= react_component('GlassySelect',
      name: 'glass_art_piece[collection_id]',
      placeholder: 'Select Collection...',
      multi: false,
      value: @pendant.collection_id,
      options: current_user.collections.all.map { |a| { value: a.id, label: a.name} })
    %>

    <%= f.input :name %>

  <label for="glass_art_piece[colors_ids][]">
    Colors
  </label>
  <input type="hidden" name="glass_art_piece[colors_ids][]" value="" />
    <%= react_component('GlassySelect',
        name: 'glass_art_piece[color_ids][]',
        placeholder: 'What colors is this piece made of?',
        multi: true,
        value: @pendant.color_ids,
        options: Color.all.map { |a| { value: a.id, label: a.name} })
    %>

  <%= f.submit %>
<% end %>

app/views/current_user/pendants/show.html.erb
<%= content_for :active_tab, :pendants %>

<div id="pendant">
  <h1><%= @pendant.name %></h1>
  <h2><%= @pendant.artist_name %></h2>

  <h3>
    <% @pendant.colors.sort_by(&:name).each_with_index do |color, i| %>
      <%= link_to color.name, color_path(color) %>
      <%= ' - ' unless @pendant.colors.count - 1 == i %>
    <% end %>
  </h3>
  <%= link_to 'Create and Add Color', new_my_pendant_colors_path(@pendant) %>
  <br />

  <%= link_to 'Edit', edit_my_pendant_path(@pendant) %>

  <h4>Times Worn: <%= @pendant.pendant_records.count %></h4>

  <div class="pendant-records card-columns">
    <%= render partial: 'pendant_record', collection: @pendant.pendant_records.by_worn_on %>
  </div>
</div>