config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get 'loaderio-6740bbace59df2ad01bb669b65e8333e', controller: :loader_io, action: :verify

  resources :passwords, controller: 'clearance/passwords', only: %i(new create)
  resource :session, controller: 'clearance/sessions', only: %i(create) do
    resource :u2f, controller: 'u2f_sessions', only: %i(new create)
  end

  resources :users, controller: 'clearance/users', only: %i(create) do
    resource :password,
             controller: 'clearance/passwords',
             only: %i(create edit update)
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out_get'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  resources :artists, only: %i(new create index)
  resources :collections, only: %i(show edit update new create) do
    resources :pendants, only: %i(show)
  end

  resources :colors, only: %i(index show new create)

  namespace :my, module: :current_user do
    resources :pendants, only: %i(new create index show edit update) do
      resource :colors, only: %i(new create), controller: 'pendant_colors'
    end
    resources :pendant_records, only: %i(new create index)
    resources :fake_pendant_records, only: %i(new create)
    resources :artists, only: %i(index)

    resource :last_week_in_pendants, only: %i(show)

    resources :u2f_registrations, only: %i(new create)

    resource :settings, only: %i(show)
  end

  namespace :api do
    namespace :my, module: :current_user do
      resources :push_notification_subscriptions, only: %i(create)
      resource :pendant_record_status, only: %i(show)
    end
  end
end

app/models/color.rb
# frozen_string_literal: true

class Color < ApplicationRecord
  belongs_to :artist_group
  belongs_to :sample_photo, class_name: 'Photo'
  has_many :artists, through: :artist_group

  has_many :glass_art_piece_colors
  has_many :glass_art_pieces, through: :glass_art_piece_colors

  def artist_ids=(artist_ids)
    self.artist_group = ArtistGroup.find_or_initialize_by_artist_ids(artist_ids)
  end

  class Params
    def initialize(params = {})
      @params = params.to_h
    end

    def attrs
      params.merge(overrides).compact
    end

    def overrides
      {
        artist_ids: artist_ids,
        name: name
      }
    end

    private

    attr_reader :params

    def artist_ids
      params[:artist_ids].select(&:present?).map(&:to_i) if params.include?(:artist_ids)
    end

    def name
      params[:name].strip if params.include?(:name)
    end
  end
end

app/controllers/colors_controller.rb
# frozen_string_literal: true

class ColorsController < ApplicationController
  def index
    @colors = Color.all
  end

  def show
    @color = Color.find params[:id]
  end

  def new
    @color = Color.new
  end

  def create
    photo = Photo.new photo_params
    @color = Color.new color_params
    @color.sample_photo = photo if photo.valid?
    if @color.save
      redirect_to action: :index
    else
      render :new
    end
  end

  private

  def color_params
    Color::Params.new(params.require(:color).permit(:name, artist_ids: [])).attrs
  end

  def photo_params
    params.require(:color).permit(:photo)
  end
end

app/views/colors/_color.html.erb
<h1><%= color.name %></h1>

<h2><%= color.artist_group.name %></h2>

<% if color.sample_photo.present? %>
  <%= image_tag color.sample_photo.url, class: '', data: { src: color.sample_photo.url } %>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist Name</th>
      <th>Colors</th>
      <th>Times Worn</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'current_user/pendants/pendant_row', collection: color.glass_art_pieces, as: :pendant %>
  </tbody>
</table>

app/views/colors/_color_row.html.erb
<tr>
  <td><%= link_to color.name, color_path(id: color.id) %></td>
  <td><%= color.glass_art_pieces.count %></td>
</tr>

app/views/colors/_form.html.erb
<%= simple_form_for color do |f| %>
  <%= f.input :name %>

  <label for="color[artist_ids][]">
    Artists
  </label>
  <input type="hidden" name="color[artist_ids][]" value="" />
  <%= react_component('GlassySelect',
      name: 'color[artist_ids][]',
      placeholder: 'Who made this pendant?',
      multi: true,
      value: color.artist_ids,
      options: Artist.all.map { |a| { value: a.id, label: a.name} })
  %>

  <%= f.input :photo, as: :photo %>

  <%= f.submit %>
<% end %>

app/views/colors/index.html.erb
<%= link_to 'New Color', new_color_path %>
<div class="colors">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th># of Glass Art Pieces</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'color_row', collection: @colors, as: :color %>
      </tbody>
    </table>
  </div>
</div>

app/views/colors/new.html.erb
<%= render partial: 'form', locals: { color: @color } %>

app/views/colors/show.html.erb
<%= render partial: @color %>